services:
  pip-compile:
    entrypoint:
      - /home/python/venv/bin/pip-compile
    image: ghcr.io/williamjacksn/pip-tools:py3.13
    init: true
    volumes:
      - ./:/home/python/databricks-sql-scripts
    working_dir: /home/python/databricks-sql-scripts

  shell:
    entrypoint:
      - /bin/bash
    image: ghcr.io/informatica-na-presales-ops/databricks-sql-scripts
    init: true
    volumes:
      - ./:/home/python/databricks-sql-scripts
